[project]
name = "XspecT"
version = "0.7.4"
description = "Tool to monitor and characterize pathogens using Bloom filters."
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
requires-python = ">=3.10,<3.14"
dependencies = [
  "biopython==1.88",
  "requests==2.34.2",
  "scikit-learn==1.9.0",
  "Bio==1.8.3",
  "loguru==0.7.3",
  "click==8.4.2",
  "python-slugify==8.0.4",
  "cobs-reloaded==0.1.1",
  "rbloom==1.5.4",
  "xxhash==4.0.1",
  "fastapi==0.141.1",
  "uvicorn==0.52.4",
  "python-multipart==0.0.32",
  "mappy==2.31",
  "pysam==0.24.0",
  "numpy==2.5.2"
  ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "License :: OSI Approved :: MIT License",
]

[project.urls]
Repository = "https://github.com/BIONF/XspecT2.git"

[project.scripts]
xspect = "xspect.main:cli"

[build-system]
requires = [
  "setuptools >= 61.0",
  "setuptools-scm>=8.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["xspect"]
namespaces = false

[tool.setuptools.package-data]
xspect = ["xspect-web/dist/**/*"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[project.optional-dependencies]
docs = ["mkdocs-material", "mkdocs-include-markdown-plugin"]
test = ["pytest", "pytest-cov", "pytest-retry", "httpx2"]
